name: Hello world
on: 
  push:
    branches: 
      - main
  workflow_dispatch:

job:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo command
        run: echo "this is test"
  
